# This file is automatically generated by pyo3_stub_gen

import typing

from nautilus_trader import model
from nautilus_trader import network

__all__ = [
    "PREDICTFUN",
    "PREDICTFUN_VENUE",
    "PredictFunDataClientConfig",
    "PredictFunDataClientFactory",
    "PredictFunExecClientConfig",
    "PredictFunExecutionClientFactory",
]

PREDICTFUN: str
PREDICTFUN_VENUE: model.Venue

@typing.final
class PredictFunDataClientConfig:
    def __init__(
        self,
        environment: str | None = None,
        api_key: str | None = None,
        api_url: str | None = None,
        websocket_url: str | None = None,
        market_filters: typing.Mapping[str, str] | None = None,
        update_instruments_interval_mins: int | None = None,
        request_timeout_secs: int | None = None,
        transport_backend: network.TransportBackend | None = None,
    ) -> None: ...

@typing.final
class PredictFunDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class PredictFunExecClientConfig:
    def __init__(
        self,
        trader_id: str | None = None,
        account_id: str | None = None,
        environment: str | None = None,
        api_key: str | None = None,
        private_key: str | None = None,
        account_address: str | None = None,
        account_type: str | None = None,
        api_url: str | None = None,
        websocket_url: str | None = None,
        rpc_url: str | None = None,
        market_slippage_bps: int | None = None,
        request_timeout_secs: int | None = None,
        transport_backend: network.TransportBackend | None = None,
    ) -> None: ...

@typing.final
class PredictFunExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
